### ISSUE TITLE
Custom slots (re-rendering) is re-fetching every options request

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FormBuilder#62] opened 2019-02-28 09:43 UTC
This is (likely) an **upstream bug & feature request**. (related to this Vue [issue](https://github.com/vuejs/vue/issues/6351))

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When changing any data in a slot this causes a re-render of the parent (`<enso-form>`), this is due to Vue behaviour which is _fixed_ only for statically defined slots at this point (see issue above).

The main issue this causes is that all `SelectField`'s are re-fetching their data.

### Steps to Reproduce
1. Have a custom slot that contains changable data (f.e. a sum sourced by the defined select)
2. Note that changing the value causes all forms to fetch data from the server again

### Expected behavior
Updating a _simple string_ not to refetch options of all fields in the form

### Actual behavior

All select fields fetch data again, even if no parameters are changes

### Suggestion

As this is most likely caused by Vue.js (2.0) behaviour, change the way SelectField fetches data (bubble up?) when used inside an EnsoForm (use the EnsoForm instance as a cache?)
To keep separation, preserve current behaviour if the _caching_ property is unavailable.

I hope there's a _better_ way as I fully understand this can't be ideal, but the limitations caused by the dynamically generated slots regenerating the whole form heavily limits the flexibility, especially when dealing with complex forms.

**Comment by aocneanu** [comment] 2019-03-05 04:46
I'll have to reproduce that on the new version

**Comment by aocneanu** [comment] 2019-03-11 07:12
Unable to reproduce it.

**Comment by jlsjonas** [comment] 2019-03-11 08:24
I'll try to reproduce the issue once the new version is out and try to pin down the cause if not (though as mentioned in the OP from it's description it seems to be a Vue2.x-related issue

**Comment by aocneanu** [comment] 2019-03-12 11:36
fixed with https://github.com/enso-ui/select/commit/984f44b8c4bbf0ef7c29633aabb2da63c2edbc06

**Closed by aocneanu** 2019-03-12 11:36 UTC

**Comment by jlsjonas** [comment] 2019-04-09 08:57
For anyone stumbling upon this in the future: using object litterals (`{ something: '123'}`) in params, custom-params, ... is causing vue to assume it's an updated entity on every ui update (since Vue2.x); which was likely the root cause of this issue.

Fix: use computed properties instead
